### PR TITLE
Update projects.yaml & make minor improvements

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
# Changes

- Added new sections (Go, Puppet, HCL, Groovy, Jupyter Notebook) 
- Added new icons (Go, Groovy, Jupyter Notebook) 
- Replaced "Select a Language" with "Select a Language or Tool" in intro.html file
- Added new projects

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@tudi2d kindly look into this please

**Comment by abhilipsasahoo03** [comment]
Hi @tudi2d @dzolotusky kindly review

**Comment by abhilipsasahoo03** [comment]
Hey @tudi2d @dzolotusky please take a look!

**Comment by tudi2d** [comment]
Thanks for the PR & sorry for no response. We had an effort & cleaning up/archiving a bunch of projects and I updated it respectively here. Closing this PR now.

**Pull request closed without merging**
